[package]
name = "fna3d-imgui"
version = "0.1.0"
authors = ["toyboot4e <toyboot4e@gmail.com>"]
edition = "2018"

[dependencies]
imgui = "0.5.0"
fna3d = { path = "../fna3d", version = "0.1.5" }
sdl2 = "0.34.3"

thiserror = "1.0.20"
log = "0.4.11"
