= WIP!!!!

Currently I'm trying to make an FNA-like framework and to improve this crate.

I'm really not sure about dynamic libraries, Rust FFI and even FNA3D. I need much more time or help!

== Getting started?

Nothing is ready!!! But at least I could call version printing function in FNA3D on macOS (see the test function in `fna3d-sys/lib.rs`).

=== Setting up dependency to FNA3D

I'm really not sure about dynamic libraries and currently FNA3D is cloned into `fna3d-sys`:

```sh
$ git clone 'https://github.com/toyboot4e/rust-fna3d'
$ cd rust-fna3d/crates/fna3d-sys
$ git clone --recursive 'https://github.com/FNA-XNA/FNA3D'
$ cd FNA3D/MojoShader && cmake
$ cd ../
$ mkdir build
$ cd build && cmake ../ && make
```

= Rust-FNA3D

Bindings for https://github.com/FNA-XNA/FNA3D[FNA3D] in Rust

== Overview

Rust-FNA3D is a safe & handy wrapper around FNA3D in Rust. It's intended be used to make an FNA-like framework.

=== What is FNA3D?

https://github.com/FNA-XNA/FNA[FNA] is a reimplementation of the http://en.wikipedia.org/wiki/Microsoft_XNA[Microsoft XNA Game Studio 4.0 Refresh] libraries. FNA3D is the 3D graphics library for FNA written in C99, which corresponds to https://docs.microsoft.com/en-us/previous-versions/windows/silverlight/dotnet-windows-silverlight/bb197344(v=xnagamestudio.35)[Microsoft.Xna.Framework.Graphics Namespace].

// === Where is an FNA-like framework?
//
// I would make one named Anf.
//
// === Where is a Nez-like framework on Rust?
//
// I would make one named Zen.
