= WIP!!!!

== TODOs

* [ ] automatically solve dependency to FNA3D
* [ ] make an FNA-like framework using this crate

== Getting started?

It onlt works on macOS for now.

=== Setting up dependency to FNA3D

I'm really not sure about dynamic libraries and currently FNA3D is cloned into `fna3d-sys`:

```sh
$ git clone 'https://github.com/toyboot4e/rust-fna3d'
$ cd rust-fna3d/fna3d-sys
$ git clone --recursive 'https://github.com/FNA-XNA/FNA3D'
$ cd FNA3D/MojoShader && cmake
$ cd ../
$ mkdir build && cd build
$ cmake ../ && make
```

And the built library is used directly (it's not copied to output directory).

= Rust-FNA3D

Wrapper of https://github.com/FNA-XNA/FNA3D[FNA3D] in Rust

== Overview

It's intended be used to make an FNA-like framework.

=== What is FNA3D?

https://github.com/FNA-XNA/FNA[FNA] is a reimplementation of the http://en.wikipedia.org/wiki/Microsoft_XNA[Microsoft XNA Game Studio 4.0 Refresh] libraries. FNA3D is the 3D graphics library for FNA written in C99, which is used to implement the FNA's https://docs.microsoft.com/en-us/previous-versions/windows/silverlight/dotnet-windows-silverlight/bb197344(v=xnagamestudio.35)[Graphics] namespace.

=== Why is a wrapper needed?

Because Rust relies on a strict type system which is different from C's one.

Note that Rust-FNA3D does NOT consider `Drop` and lifetimes, and they are delegated to a framework on top of it.

== References

=== Framework using FNA3D

I'm making one.

=== Other repositories using FNA3D

* https://gist.github.com/jessechounard/d4252efc12ee24494484611d92b1debe[Simple texture rendering in FNA3D] \(C)
* https://github.com/silenttowergames/stonetower[Stonetower] \(C)
* https://github.com/KillaMaaki/BNA[BNA] (https://www.beeflang.org/[Beef])
* https://github.com/prime31/Odin-Libs[Odin-Libs] (https://odin-lang.org/[Odin])
* https://github.com/prime31/via[Via] (https://vlang.io/[V])

==== Other C graphics libraries

* https://github.com/floooh/sokol[Sokol]
+
A minimal cross-platform standalone C headers
