//! Wrapper of FNA3D, which corresponds to `Microsoft.Xna.Framework.Graphics` namespace (?)
//!
//! This crate was mainly generated by [`bindgen`](https://crates.io/crates/bindgen). `fna3d`
//! corresponds to `FNA3D.h` and `fna3d::img` corresponds to `FNA3D_Image.h`.
//!
//! Internally, `build.rs` uses `bindgen` to generate forengin function interface in `ffi`.
//! Those bindings gemerated are autimatically included. If you want to see the generated file,
//! you can find it in `target`, or you can install the `bindgen` command line tool via `cargo` and
//! run it over a wrapping header file.

mod fna3d_enums;
mod fna3d_functions;
mod fna3d_structs;

// FNA3D.h
pub use fna3d_enums::*;
pub use fna3d_functions::*;
pub use fna3d_structs::*;

// FNA3D_Image.h
pub use fna3d_structs::img;
