[package]
name = "fna3d"
version = "0.1.0"
authors = ["toyboot4e <toyboot4e@gmail.com>"]
edition = "2018"

[dependencies]
enum_primitive = "0.1.1"
fna3d-sys = { path = "../fna3d-sys" }
bitflags = "1.2.1"
log = "0.4.8"
