[package]
name = "fna3d-sys"
version = "0.1.0"
authors = ["toyboot4e <toyboot4e@gmail.com>"]
edition = "2018"

[lib]
name = "fna3d_sys"
path = "src/lib.rs"

[build-dependencies]
bindgen = "0.54.0"

[dependencies]
